import simpleGit, { SimpleGit } from 'simple-git';

function getGit(): SimpleGit {
  return simpleGit(process.cwd());
}

export async function isGitRepo(): Promise<boolean> {
  try {
    await getGit().status();
    return true;
  } catch {
    return false;
  }
}

export async function getCurrentBranch(): Promise<string> {
  const status = await getGit().status();
  return status.current || 'unknown';
}

export async function getModifiedFiles(): Promise<string[]> {
  const status = await getGit().status();
  return [
    ...status.modified,
    ...status.created,
    ...status.not_added
  ];
}

export async function commitSessionReport(
  reportPath: string,
  sessionId: string
): Promise<void> {
  const git = getGit();
  await git.add(reportPath);
  await git.commit(`docs: add AI session report ${sessionId}\n\nGenerated by starterkit session tracker.`);
}

export async function getRecentCommits(count: number = 5): Promise<string[]> {
  const log = await getGit().log({ maxCount: count });
  return log.all.map(commit => commit.message);
}
